name: Build and Release

on:
  release:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Restore Cache for `build`
        uses: actions/cache@v2.1.6
        with:
          path: build
          key: ${{ runner.os }}-cache
      
      - name: Setup CMake
        uses: lukka/get-cmake@latest
      
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows'
        with:
          update: true
          install: >-
            base-devel
            git
      
      - name: Configure CMake and Build
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
          cmakeBuildType: Release
          buildDirectory: build
          
      - name: Move Executable to `artifact`
        shell: bash
        run: |
          mkdir artifact
          cp build/app/app* artifact
          ls -lA artifact
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          path: artifact
          name: ${{ runner.os }}-artifact
          
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        if: ${{ github.event_name == 'release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: artifact
          asset_name: minisql-${{ runner.os }}
